import { ThemeStyles } from "@/typing";
export const defaultNavConfig = [
    {
        id: "1",
        name: "主页",
        icon: "home",
        children: [
            {
                name: "i天气",
                component: "weather",
                type: "component",
                size: "2x4",
                id: "boeg77UMK",
                view: 3,
            },
            {
                name: "热搜榜",
                component: "topsearch",
                type: "component",
                size: "2x4",
                id: "4YROGDwnK",
                view: 8,
            },
            {
                name: "i日历",
                component: "calendar",
                type: "component",
                size: "2x2",
                id: "gSZZkzSIL",
                view: 4,
            },
            {
                component: "daysMatter",
                insetType: "",
                name: "倒数日",
                src: "https://files.codelife.cc/tools-icon/daysMatter.svg",
                type: "component",
                config: {
                    name: "纪念日",
                    title: "你在世界已经",
                    target: "1997-10-1",
                    repeat: "",
                    bgColor: "https://files.codelife.cc/itab/widget/yiyan/12.jpg",
                    textColor: "#ffffff",
                    family: "",
                    icon: "",
                    mask: "",
                },
                size: "2x2",
                id: "u8vVYeSTlmoebAtAVrfSq9094",
                view: 3,
            },
            {
                id: "Mh9M0gUXe6N-TjKfMaGx_",
                url: "https://ai.taobao.com?pid=mm_54561194_2536750027_111828300388&union_lens=lensId%3APUB%401644727921%4021057ef3_09a7_17ef16c69e2_05aa%4001",
                type: "icon",
                name: "淘宝",
                src: "https://files.codelife.cc/icons/taobao.svg",
                backgroundColor: "#f52324",
                view: 8,
                iconText: "爱淘宝",
            },
            {
                id: "5yEZm2kln",
                url: "https://www.itab.link/web/jd.html",
                type: "icon",
                name: "京东商城",
                src: "https://files.codelife.cc/icons/jd.svg",
                backgroundColor: "#ff0000",
                view: 6,
            },
            {
                id: "glN0dLcwF",
                url: "https://www.baidu.com/?tn=15007414_20_dg",
                type: "icon",
                name: "百度",
                src: "https://files.codelife.cc/icons/baidu.svg",
                backgroundColor: "#346efd",
                view: 2,
                iconText: "百度",
            },
            {
                id: "5a94d582e753876b29cffb95",
                type: "icon",
                url: "https://www.tmall.com/",
                name: "天猫精选",
                src: "https://files.codelife.cc/icons/tmall.svg",
                backgroundColor: "#ff0030",
                view: 2,
            },
            {
                component: "countdown",
                name: "下班倒计时",
                size: "2x4",
                type: "component",
                id: "XH4chhkPCCynjgtUk2Ued",
                view: 0,
            },
            {
                name: "电影日历",
                component: "movieCalendar",
                type: "component",
                insetType: "",
                src: "https://files.codelife.cc/tools-icon/movieCalendar.svg",
                size: "2x2",
                id: "AMCmO0mTkAuDbfFxG9XVK8222",
            },
            {
                name: "备忘录",
                component: "notes",
                type: "component",
                size: "2x2",
                id: "pLm0V9msZ",
                view: 4,
            },
            {
                url: "https://www.douyin.com/?ug_source=pc_liangxiang_01",
                type: "icon",
                name: "抖音",
                src: "https://files.codelife.cc/website/douyin.svg",
                backgroundColor: "#1c0b1a",
                id: "ZZvJuRkzaciKud2lW3EH_5544",
                iconText: "抖音",
                view: 4,
            },
            {
                url: "https://metaso.cn/?s=itaber&referrer_s=itaber",
                type: "icon",
                name: "秘塔AI搜索",
                src: "https://files.codelife.cc/icons/metaso.cn.png",
                backgroundColor: "#ffffff",
                id: "EkqMR0tOtFarPEgyt6KOj9383",
            },
            {
                url: "https://www.meijian.com/mj/meijian/site-v2/member/activity/e-commerce/reg-promotion?utm_source=dsdhxbqitab",
                type: "icon",
                name: "美间AI设计",
                src: "https://files.codelife.cc/icons/meijian.png",
                backgroundColor: "#fff",
                id: "hO589JfP5irlnHPd_39rm7782",
            },
            {
                url: "https://ibiling.cn/paper?from=itabpaper02",
                type: "icon",
                name: "专业AI论文写作",
                src: "https://files.codelife.cc/icons/biling.cn.svg",
                backgroundColor: "#00b178",
                id: "cqhMMBl-r40GRsb-KA9Xn7237",
                iconText: "专业A",
                view: 1,
            },
            {
                id: "29YCEZ6uQ",
                url: "http://weibo.com/",
                type: "icon",
                name: "新浪微博",
                src: "https://files.codelife.cc/icons/weibo.svg",
                backgroundColor: "#ffd850",
            },
            {
                url: "https://chatglm.cn/apps?image=https%3A%2F%2Fsfile.chatglm.cn%2Factiveimg%2Fbdms%2F66b97e348217030036f486f1&open_from=ads_web_itab&fr=ads_web_itab",
                type: "icon",
                name: "智谱清言",
                src: "https://files.codelife.cc/icons/chatglm.cn.png",
                backgroundColor: "#ffffff",
                id: "tNGJQKHkPJxEs7N2vrgSY9358",
                iconText: "智谱清",
                view: 1,
            },
            {
                url: "https://www.ihuiwa.com/invite?huiwaInviteCode=EMUX7L",
                type: "icon",
                name: "阿里绘蛙",
                src: "https://files.codelife.cc/icons/ihuiwa.jpg",
                backgroundColor: "#fff",
                id: "zmttd9JWCVpxCzBq6rLkW9859",
            },
            {
                name: "i壁纸",
                component: "wallpaper",
                type: "icon",
                size: "1x1",
                id: "fu2M-S9yd",
                src: "https://files.codelife.cc/tools-icon/wallpaper.svg",
                view: 2,
            },
            {
                url: "https://pptgo.cn/?utm_source=Itab&_channel_track_key=ZIJxLllr",
                type: "icon",
                name: "博思AIPPT",
                src: "https://files.codelife.cc/icons/pptgo.cn.webp",
                backgroundColor: "",
                id: "Og6n-Dm7WdoFCcFRrea_U6154",
                iconText: "博思A",
                view: 1,
            },
            {
                url: "https://ibiling.cn/template?from=itabpaper03",
                type: "icon",
                name: "免费AI写作",
                src: "https://files.codelife.cc/icons/baipingai.png",
                backgroundColor: "#ffffff",
                id: "biK41yAj1d4r0jClgH0rK9077",
                iconText: "心动A",
            },
            {
                url: "https://www.trae.com.cn/?utm_source=advertising&utm_medium=itab_ug_cpa&utm_term=hw_trae_itab",
                type: "icon",
                name: "TraeAi编辑器",
                src: "https://files.codelife.cc/icons/trae.ai.svg",
                backgroundColor: "#f1c40f",
                id: "cf31bMBR-oHhJdt_w6k6Q6408",
                iconText: "Tra",
            },
            {
                id: "vwLnQvDMr",
                url: "http://www.bilibili.com/",
                type: "icon",
                name: "哔哩哔哩",
                src: "https://files.codelife.cc/icons/bilibili2.svg",
                backgroundColor: "#fe65a6",
            },
            {
                id: "-GlRzTMT11",
                url: "https://itab.link",
                type: "icon",
                name: "iTab新标签页",
                src: "https://files.codelife.cc/icons/itab.svg",
                backgroundColor: "#1581ff",
            },
            {
                id: "tqu1Cbxtw",
                url: "https://www.zhihu.com/",
                type: "icon",
                name: "知乎",
                src: "https://files.codelife.cc/icons/zhihu.svg",
                backgroundColor: "#0c6dfe",
            },
            {
                url: "https://www.itab.link/browser.html",
                type: "icon",
                name: "iTab浏览器",
                src: "https://files.codelife.cc/icons/itab-browser.png",
                backgroundColor: "#ffffff",
                id: "t23jN_Ar3es5iB-fBIbUb9694",
                view: 2,
            },
            {
                url: "https://www.marscode.cn/?utm_source=itab.link&utm_medium=xycpa&utm_campaign=",
                type: "icon",
                name: "豆包代码助手",
                src: "https://files.codelife.cc/icons/marscode.cn.svg",
                backgroundColor: "#fff",
                id: "65XK0PGiUOFgwPHB7y8IB2286",
                iconText: "",
            },
            {
                url: "https://www.doubao.com?channel=itab2&source=hw_db_itab",
                type: "icon",
                name: "豆包-你的AI朋友",
                src: "https://files.codelife.cc/icons/doubao.com.webp",
                backgroundColor: "#ffffff",
                id: "7001H6blviCCeX-3HM6pX0404",
                view: 4,
                iconText: "豆包-",
            },
            {
                url: "https://www.xiaohongshu.com/explore?m_source=itab",
                type: "icon",
                name: "小红书",
                src: "https://files.codelife.cc/icons/xiaohongshu.svg",
                backgroundColor: "#ff2442",
                id: "xYQZ8MsluBvjC3VDGvLEK1053",
                view: 3,
            },
            {
                id: "GUeCPknZi",
                url: "https://www.iqiyi.com/?vfm=f_432_dhm&fv=8648154ddd63e0af",
                type: "icon",
                name: "爱奇艺",
                src: "https://files.codelife.cc/icons/iqiyi.svg",
                backgroundColor: "#00cc4c",
                view: 1,
            },
            {
                name: "书签管理",
                type: "icon",
                component: "bookmarks",
                size: "1x1",
                id: "ABlIiKONc4F1acq3FZU-S",
                src: "https://files.codelife.cc/tools-icon/bookmarks.svg",
                view: 2,
            },
            {
                id: "guide-1",
                url: "itab://guide",
                type: "icon",
                name: "iTab新手引导",
                src: "https://files.codelife.cc/icons/guide.svg",
                backgroundColor: "#febc04",
            },
            {
                id: "k67HgbHCCHn_wvZBHbYR-",
                url: "chrome://history/",
                type: "icon",
                name: "历史记录",
                src: "https://files.codelife.cc/icons/history.svg",
                view: 2,
                backgroundColor: "#0599d9",
            },
            {
                id: "0g75JmsYHHPQlYhpKxsBD",
                url: "chrome://extensions/",
                type: "icon",
                name: "扩展管理",
                src: "https://files.codelife.cc/icons/extensions.svg",
                backgroundColor: "#9c9c9c",
                view: 1,
            },
            {
                id: "GTIzQ7fHwS501SWtM_8H_",
                url: "itab://setting",
                type: "icon",
                name: "设置",
                src: "https://files.codelife.cc/icons/setting.svg",
                view: null,
                backgroundColor: "#fff",
            },
            {
                id: "Vpdrvg_2bvxzGiyRKEpOA",
                url: "itab://add",
                type: "icon",
                name: "添加图标",
                src: "https://files.codelife.cc/icons/add.svg",
                backgroundColor: "#fff",
                iconText: "",
            },
        ],
    },
    {
        name: "编程",
        icon: "code",
        children: [
            {
                id: "xLiON51K5",
                url: "https://www.apifox.cn/a1itabweb",
                type: "icon",
                name: "Apifox",
                src: "https://files.codelife.cc/icons/apifoxcn.svg",
                backgroundColor: "#f4425f",
            },
            {
                id: "CZHjnJIMB",
                url: "https://github.com/",
                type: "icon",
                name: "GitHub",
                src: "https://files.codelife.cc/icons/github.svg",
                backgroundColor: "#000",
            },
            {
                id: "sfPX-WRi0",
                url: "http://www.v2ex.com/",
                type: "icon",
                name: "V2EX",
                src: "https://files.codelife.cc/icons/v2ex.svg",
                backgroundColor: "#222222",
            },
            {
                id: "zsTvF1WI3",
                url: "https://zh-hans.reactjs.org/",
                type: "icon",
                name: "React",
                src: "https://files.codelife.cc/icons/react.svg",
                backgroundColor: "#27333b",
            },
            {
                id: "Svyvhe-MI",
                url: "https://mrjokersince1997.github.io/My-Notes/#/",
                type: "icon",
                name: "Java学习",
                src: "https://files.codelife.cc/icons/mrjokersince-java.svg",
                backgroundColor: "#1c1c1c",
            },
            {
                id: "yQv_IiTzL",
                url: "https://gitee.com/",
                type: "icon",
                name: "码云Gitee",
                src: "https://files.codelife.cc/icons/gitee.svg",
                backgroundColor: "#bb2124",
            },
            {
                id: "NKfU43cp6",
                url: "http://www.csdn.net/",
                type: "icon",
                name: "CSDN",
                src: "https://files.codelife.cc/icons/csdn.svg",
                backgroundColor: "#cc001b",
            },
            {
                id: "9ivZt9a2i",
                url: "http://www.w3school.com.cn",
                type: "icon",
                name: "w3school在线教程",
                src: "https://files.codelife.cc/icons/w3school.svg",
                backgroundColor: "#cc3333",
            },
            {
                id: "omCrX5KHJ",
                url: "https://stackoverflow.com/",
                type: "icon",
                name: "Stack Overflow",
                src: "https://files.codelife.cc/icons/stackoverflow.svg",
                backgroundColor: "#444444",
            },
            {
                id: "Cp9wFUk43",
                url: "https://juejin.cn/",
                type: "icon",
                name: "掘金",
                src: "https://files.codelife.cc/icons/juejin.svg",
                backgroundColor: "#0984fe",
            },
            {
                id: "zGsb_kZ9_",
                url: "https://leetcode.cn/",
                type: "icon",
                name: "力扣",
                src: "https://files.codelife.cc/icons/leetcode.svg",
                backgroundColor: "#fff",
            },
            {
                id: "lG5SopVNY",
                url: "https://cn.vuejs.org/",
                type: "icon",
                name: "Vue2",
                src: "https://files.codelife.cc/icons/vuejs.svg",
                backgroundColor: "#fff",
            },
            {
                id: "Qz-7AjQ2j-0LgOW1gvzs8",
                url: "https://arco.design",
                type: "icon",
                name: "Arco Design",
                src: "https://files.codelife.cc/icons/arco-design.svg",
                backgroundColor: "#fdfef7",
            },
            {
                id: "dGKow0Xcz",
                url: "https://www.antdv.com/docs/vue/introduce-cn/",
                type: "icon",
                name: "Ant Design Vue",
                src: "https://files.codelife.cc/icons/ant-design-vue.svg",
                backgroundColor: "#fff",
            },
            {
                id: "vjMN3-WZq",
                url: "http://www.oschina.net/",
                type: "icon",
                name: "开源中国",
                src: "https://files.codelife.cc/icons/oschina.svg",
                backgroundColor: "#34b960",
            },
            {
                id: "vflKyWV5I91jKj2XGpWp-",
                url: "https://www.asiayun.com/aff/IROSKGHJ",
                type: "icon",
                name: "亚洲云",
                src: "https://files.codelife.cc/icons/asiayun.svg",
                backgroundColor: "#fff",
                iconText: "亚云",
                view: 1,
            },
            {
                id: "geekbang-",
                url: "https://time.geekbang.org/?utm_term=iTab&utm_source=iTab&utm_medium=iTab&utm_campaign=iTab&utm_content=iTab",
                type: "icon",
                name: "极客时间",
                src: "https://files.codelife.cc/icons/geekbang.svg",
                backgroundColor: "#fff",
            },
            {
                id: "hTirVJgmj-kaifa",
                url: "https://kaifa.baidu.com/",
                type: "icon",
                name: "开发者搜索",
                src: "https://files.codelife.cc/icons/kaifa.baidu.svg",
                backgroundColor: "#fff",
            },
        ],
        id: "2",
    },
    {
        id: "nav_yepAOU0lK",
        name: "设计",
        icon: "Darw",
        children: [
            {
                id: "3NjEiwNGO",
                url: "https://www.gaoding.com/utms/cd52981c7dfe966f01ee33d63fa94183",
                type: "icon",
                name: "稿定设计",
                src: "https://files.codelife.cc/icons/gaoding.svg",
                backgroundColor: "#2455f4",
                view: 2,
            },
            {
                id: "5kGk9TzkRam-a",
                url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
                type: "icon",
                name: "即时设计",
                src: "https://files.codelife.cc/icons/jsdesign.svg",
                backgroundColor: "#cf3d35",
            },
            {
                id: "v_xMvU7V_",
                url: "http://huaban.com/",
                type: "icon",
                name: "花瓣",
                src: "https://files.codelife.cc/icons/huaban.svg",
                backgroundColor: "#ea2936",
            },
            {
                id: "raBGdwOvo",
                url: "https://www.zcool.com.cn/",
                type: "icon",
                name: "站酷",
                src: "https://files.codelife.cc/icons/zcool.svg",
                backgroundColor: "#e6be1c",
            },
            {
                id: "qW3jSNLWy",
                url: "https://dribbble.com",
                type: "icon",
                name: "Dribbble",
                src: "https://files.codelife.cc/icons/dribbble.svg",
                backgroundColor: "#f24e7c",
            },
            {
                url: "https://www.x-design.com/?channel=goitab",
                type: "icon",
                name: "美图设计室",
                src: "https://files.codelife.cc/icons/x-design.com .svg",
                backgroundColor: "#000000",
                id: "F8seeVF_iygnw9RYcGoSl2614",
            },
            {
                id: "4A9hLUKqm",
                url: "https://www.bigbigwork.com",
                type: "icon",
                name: "大作免费图片",
                src: "https://files.codelife.cc/icons/bigbigwork.svg",
                backgroundColor: "#ff4d4d",
            },
            {
                id: "SF74W_GIh",
                url: "http://www.nipic.com/index.html",
                type: "icon",
                name: "昵图网",
                src: "https://files.codelife.cc/icons/nipic.svg",
                backgroundColor: "#dd137b",
            },
            {
                id: "BLJkgf_Aw",
                url: "https://uidesigndaily.com/",
                type: "icon",
                name: "每日ui设计",
                src: "https://files.codelife.cc/icons/uidesigndaily.svg",
                backgroundColor: "#fafefe",
            },
            {
                url: "https://unsplash.dogedoge.com/",
                type: "icon",
                name: "Unsplash加速版",
                src: "https://files.codelife.cc/icons/unsplash.svg",
                backgroundColor: "#FFFFFF",
                id: "UiQz7t81324v8JV2X3DdM8575",
                iconText: "",
            },
            {
                id: "l5OAFo0I2",
                url: "https://tinypng.com",
                type: "icon",
                name: "TinyPNG",
                src: "https://files.codelife.cc/icons/60b9eba2ae5a9ba4024b3bfc.png",
                backgroundColor: "#cde7f0",
            },
            {
                id: "7U3csko_Y",
                url: "https://www.91sotu.com/",
                type: "icon",
                name: "搜图导航",
                src: "https://files.codelife.cc/icons/www.91sotu.com.svg",
                backgroundColor: "#fec20a",
            },
            {
                id: "RC4f5ycSJ",
                url: "https://www.iconfont.cn/",
                type: "icon",
                name: "Iconfont",
                src: "https://files.codelife.cc/icons/iconfont.svg",
                backgroundColor: "#ffffff",
            },
            {
                id: "2tIHIXVtj",
                url: "http://zhongguose.com/",
                type: "icon",
                name: "中国色",
                src: "https://files.codelife.cc/icons/zhongguose.com.svg",
                backgroundColor: "#dadada",
            },
            {
                id: "kKCjRYCwG",
                url: "http://www.58pic.com/",
                type: "icon",
                name: "千图网",
                src: "https://files.codelife.cc/icons/58pic.svg",
                backgroundColor: "#00a46b",
            },
            {
                url: "https://hisheai.com/?from=itab",
                type: "icon",
                name: "千图AI设计助手",
                src: "https://files.codelife.cc/icons/hisheai.svg",
                backgroundColor: "#0b62ff",
                id: "i-Q33NQLQ_GAv2PJzid7M0573",
            },
            {
                id: "hCG7key-W",
                url: "http://ibaotu.com/",
                type: "icon",
                name: "包图网",
                src: "https://files.codelife.cc/icons/ibaotu.svg",
                backgroundColor: "#fff5c8",
            },
            {
                id: "cfYmvqDNAcv-kSZAoKLu3",
                url: "http://www.qijishow.com/down/index.html",
                type: "icon",
                name: "奇迹秀",
                src: "https://files.codelife.cc/icons/qijishow.svg",
                backgroundColor: "#122441",
            },
            {
                id: "0z6-vP_7M-2",
                url: "https://www.hellofont.cn?from=itab:test",
                type: "icon",
                name: "字由字体",
                src: "https://files.codelife.cc/icons/hellofont.cn.svg",
                backgroundColor: "#403F41",
            },
            {
                id: "0z6-vP_7M-21",
                url: "https://topd.tencent.com/ai?ref=itab.link",
                type: "icon",
                name: "Top.AI",
                src: "https://files.codelife.cc/icons/top-ai.png",
                backgroundColor: "#ffffff",
            },
            {
                url: "https://www.1txm.com/?from=itab",
                type: "icon",
                name: "易条形",
                src: "https://files.codelife.cc/icons/1txm.jpg",
                backgroundColor: "#fff",
                id: "uuRgm6iHVJLnQ6Zw4qFye6338",
            },
        ],
    },
    {
        name: "产品",
        icon: "Producthunt",
        children: [
            {
                id: "vqZCrDh6zad",
                url: "https://flowus.cn/product?promotionChannel=GW_itab",
                type: "icon",
                name: "FlowUs",
                src: "https://files.codelife.cc/icons/flowus.png",
                backgroundColor: "#fff",
            },
            {
                id: "vqZCrDh6z",
                url: "https://www.notion.so/",
                type: "icon",
                name: "Notion ",
                src: "https://files.codelife.cc/icons/notion.svg",
                backgroundColor: "#fff",
            },
            {
                url: "https://www.processon.com/?utm_source=itab",
                type: "icon",
                name: "思维导图流程图",
                src: "https://files.codelife.cc/icons/processon.png",
                backgroundColor: "#1985f0",
                id: "lYxszRKo_RNs2gf9B0uoZ9054",
                iconText: "Pro",
            },
            {
                url: "https://www.officeplus.cn/",
                type: "icon",
                name: "PPT神器",
                src: "https://files.codelife.cc/icons/officeplus.cn.svg",
                backgroundColor: "#ffffff",
                id: "yGCkjz8yG0AjCwRx61s3r5694",
                view: 1,
            },
            {
                id: "-wDKDVcMeU3Ptykw-F0aF",
                url: "https://u.tools/?from=itab",
                type: "icon",
                name: "uTools",
                src: "https://files.codelife.cc/icons/utools.svg",
                backgroundColor: "#fff",
            },
            {
                url: "https://xiezuocat.com/?s=itab",
                type: "icon",
                name: "秘塔写作猫",
                src: "https://files.codelife.cc/icons/xiezuocat.com.svg",
                id: "6q1euMaEjtzT7K8oosijk5045-2",
                view: 0,
                backgroundColor: "#fefefe",
            },
            {
                id: "zE9RKmF0l",
                url: "https://shimo.im/desktop",
                type: "icon",
                name: "石墨文档",
                src: "https://files.codelife.cc/icons/shimo.svg",
                backgroundColor: "#fff",
            },
            {
                id: "NxcUMe4w5",
                url: "https://www.iconfont.cn/",
                type: "icon",
                name: "Iconfont",
                src: "https://files.codelife.cc/icons/iconfont.svg",
                backgroundColor: "#ffffff",
            },
            {
                id: "HXATd_798",
                url: "http://www.36kr.com",
                type: "icon",
                name: "36氪",
                src: "https://files.codelife.cc/icons/36kr.svg",
                backgroundColor: "#1380d8",
            },
            {
                id: "KHigwIg9e",
                url: "https://www.zhixi.com/?utm_source=webaff&id=Zx7wbwin",
                type: "icon",
                name: " 知犀思维导图",
                src: "https://files.codelife.cc/icons/zhixi.svg",
                backgroundColor: "#4dec7c",
            },
            {
                url: "https://sspai.com/?utm_source=itab.ink",
                type: "icon",
                name: "少数派",
                src: "https://files.codelife.cc/icons/sspai.svg",
                id: "3OaNFoVII7bWIDIzqXhYX6675",
                backgroundColor: "#d7191a",
            },
            {
                url: "https://www.crxsoso.com/?utm=itab",
                type: "icon",
                name: "扩展搜搜",
                src: "https://files.codelife.cc/icons/crxsoso.com.svg",
                id: "crxsoso-1",
                backgroundColor: "#fff",
            },
            {
                url: "https://www.islide.cc/ppt?utm_source=itab&utm_medium=web&utm_campaign=1",
                type: "icon",
                name: "iSlide PPT神器",
                src: "https://files.codelife.cc/icons/islide.svg",
                id: "iSlide-1",
                backgroundColor: "#fff",
                view: 1,
            },
            {
                url: "https://boardmix.cn/",
                type: "icon",
                name: "boardmix白板",
                src: "https://files.codelife.cc/icons/boardmix.cn.svg",
                id: "boardmix-2",
                backgroundColor: "#fff",
            },
            {
                id: "writingo-2",
                url: "https://www.writingo.net/document?source=itab",
                type: "icon",
                name: "英语润色",
                src: "https://files.codelife.cc/icons/writingo.net.svg",
                backgroundColor: "#fff",
            },
            {
                id: "hbPSc5kFD",
                url: "https://www.67tool.com/?from=itab.link",
                type: "icon",
                name: "即时工具",
                src: "https://files.codelife.cc/icons/67tool.svg",
                backgroundColor: "#369dfc",
            },
            {
                url: "https://axmax.cn?utm_source=itab",
                type: "icon",
                name: "原型托管",
                src: "https://files.codelife.cc/icons/axmaxcn.svg",
                id: "axmax",
                backgroundColor: "#ffffff",
            },
            {
                url: "https://cv.ibiling.cn/?from=itab",
                type: "icon",
                name: "心动AI简历",
                src: "https://files.codelife.cc/icons/cv.ibiling.cn.webp",
                backgroundColor: "#ffffff",
                id: "eVliIqrUh81LSf2P2-eYe2781",
            },
            {
                id: "4IM79snuL",
                url: "http://www.woshipm.com/",
                type: "icon",
                name: "人人都是产品经理",
                src: "https://files.codelife.cc/icons/woshipm.svg",
                backgroundColor: "#fff",
            },
        ],
        id: "nav_v1yD3mRTC",
    },
    {
        id: "nav_ZLL8ueRdj8VpYbAOPKR1S0699",
        name: "AI",
        icon: "ApiApp",
        children: [
            {
                url: "https://ai-bot.cn/?utm_source=itab",
                type: "icon",
                name: "AI工具集",
                src: "https://files.codelife.cc/icons/ai-bot.svg",
                backgroundColor: "#0071c0",
                id: "SO0MxdvOyceJuAP_HNp306267",
                view: 2,
                iconText: "豆包 ",
            },
            {
                url: "https://metaso.cn/?s=itaber&referrer_s=itaber",
                type: "icon",
                name: "秘塔AI搜索",
                src: "https://files.codelife.cc/icons/metaso.cn.png",
                backgroundColor: "#ffffff",
                id: "dbc658-yCnYPB9Uu8x8Y01201",
                iconText: "秘塔A",
            },
            {
                url: "https://xiezuocat.com/?s=itab",
                type: "icon",
                name: "秘塔写作猫",
                src: "https://files.codelife.cc/icons/xiezuocat.com.svg",
                backgroundColor: "#fefefe",
                id: "WU5cPaye_efmmAvJ4lK3D5835",
                view: 3,
            },
            {
                url: "https://www.meijian.com/mj/meijian/site-v2/member/activity/e-commerce/reg-promotion?utm_source=dsdhxbqitab",
                type: "icon",
                name: "美间AI设计",
                src: "https://files.codelife.cc/icons/meijian.png",
                backgroundColor: "#fff",
                id: "1deA65dF21R_qcd-JZFFH3555",
            },
            {
                url: "https://kimi.moonshot.cn/?utm_campaign=TR_90K51izQ&utm_content=&utm_medium=%E7%BA%BF%E4%B8%8ACPA&utm_source=CH_AwqiWw8L&utm_term=",
                type: "icon",
                name: "Kimi",
                src: "https://files.codelife.cc/icons/kimi.moonshot.png",
                backgroundColor: "#054092",
                id: "kYDrBNXLQbJdxqWAUReRm2875",
                iconText: "Kim",
            },
            {
                url: "https://www.aippt.cn/?seller=itab",
                type: "icon",
                name: "AI免费生成PPT",
                src: "https://files.codelife.cc/icons/aippt.cn.png",
                backgroundColor: "#fff",
                id: "LdTdDBXXs1vu69v8mImjK7694",
                iconText: "",
            },
            {
                url: "https://www.deepseek.com/",
                type: "icon",
                name: "DeepSeek",
                src: "https://files.codelife.cc/icons/deepseek.svg",
                backgroundColor: "#fff",
                id: "Ns2VOBuus1ji4JxQXlHHL7006",
            },
            {
                url: "https://jimeng.jianying.com/ai-tool/home/?utm_medium=aitools&utm_source=itab&utm_campaign=null&utm_content=49220815g",
                type: "icon",
                name: "即梦AI",
                src: "https://files.codelife.cc/icons/jimeng.jianying.png",
                backgroundColor: "",
                id: "p5ZH7tcFPgxFxT2Bast183278",
            },
            {
                url: "https://ibiling.cn/paper?from=itabpaper02",
                type: "icon",
                name: "专业AI论文写作",
                src: "https://files.codelife.cc/icons/biling.cn.svg",
                backgroundColor: "#00b178",
                id: "xAgiltMGYSXIVL-oDXeT54859",
                iconText: "专业A",
                view: 4,
            },
            {
                url: "https://pptgo.cn/?utm_source=Itab&_channel_track_key=ZIJxLllr",
                type: "icon",
                name: "博思AIPPT",
                src: "https://files.codelife.cc/icons/pptgo.cn.webp",
                backgroundColor: "#023373",
                id: "n9-L5S3SthZgAb36zXfjb9802",
                iconText: "",
            },
            {
                url: "https://www.mindshow.fun/#/home?inviteCode=itab",
                type: "icon",
                name: "mindshow",
                src: "https://files.codelife.cc/icons/mindshow.fun.svg",
                backgroundColor: "#ffffff",
                id: "g3UExqf67PBV4W1GzzdYP0696",
                view: 2,
            },
            {
                url: "https://www.aipaperpass.com?pic=xQN6",
                type: "icon",
                name: "AI一键论文",
                src: "https://files.codelife.cc/icons/aipaperpass.png",
                backgroundColor: "#fff",
                id: "dkeucOHuzJQLRHhd-7K7M2546",
            },
            {
                url: "https://chatglm.cn/apps?image=https%3A%2F%2Fsfile.chatglm.cn%2Factiveimg%2Fbdms%2F66b97e348217030036f486f1&open_from=ads_web_itab&fr=ads_web_itab",
                type: "icon",
                name: "智谱清言",
                src: "https://files.codelife.cc/icons/chatglm.cn.png",
                backgroundColor: "#ffffff",
                id: "f9D3-8gOjsr0SbApe3YnG9294",
            },
            {
                url: "https://www.ihuiwa.com/invite?huiwaInviteCode=EMUX7L",
                type: "icon",
                name: "阿里绘蛙",
                src: "https://files.codelife.cc/icons/ihuiwa.jpg",
                backgroundColor: "#fff",
                id: "ieIfvYqKMJmvnsgczB4kF7028",
            },
            {
                url: "https://www.coze.cn/?utm_medium=daohang&utm_source=itab&utm_content=home&utm_id=0&utm_campaign=&utm_term=49156769k&utm_source_platform=",
                type: "icon",
                name: "扣子",
                src: "https://files.codelife.cc/icons/coze.cn.svg",
                backgroundColor: "#4d53e8",
                id: "Iv8H9pHSRHx-roruQfxi75847",
            },
            {
                url: "https://boardmix.cn/mindmapping/",
                type: "icon",
                name: "Ai思维导图",
                src: "https://files.codelife.cc/icons/boardmix.svg",
                backgroundColor: "#ffffff",
                id: "YpCGR-aAM8KYQQLZ6fhR51423",
                view: 2,
            },
            {
                url: "https://www.aippt.cn/?seller=itab",
                type: "icon",
                name: "AiPPT",
                src: "https://files.codelife.cc/icons/aippt.cn.png",
                backgroundColor: "#fff",
                id: "O1lCBJIifuQcTMCli3_Fg7201",
            },
            {
                url: "https://www.marscode.cn/?utm_source=itab.link&utm_medium=xycpa&utm_campaign=",
                type: "icon",
                name: "豆包代码助手",
                src: "https://files.codelife.cc/icons/marscode.cn.svg",
                backgroundColor: "#fc4548",
                id: "7xu5fW3BGzdr7GVj29jRW0577",
                iconText: "",
            },
            {
                url: "https://xinghuo.xfyun.cn/desk?ch=xhweb_ril",
                type: "icon",
                name: "讯飞星火",
                src: "https://files.codelife.cc/icons/xinghuo.xfyun.cn.png",
                backgroundColor: "#fff",
                id: "AKSrinXrPaBEV51pZH8pP6334",
                view: 1,
                iconText: "讯飞星",
            },
            {
                url: "https://ai.openmao.cn/",
                type: "icon",
                name: "开放猫",
                src: "https://files.codelife.cc/icons/openmao.panchuang.net.png",
                backgroundColor: "#ffffff",
                id: "Rp4zGHffWdBN90phkeup59951",
            },
            {
                url: "https://www.doubao.com?channel=itab2&source=hw_db_itab_01",
                type: "icon",
                name: "豆包",
                src: "https://files.codelife.cc/icons/doubao.com.webp",
                backgroundColor: "#ffffff",
                id: "eBwy8XrYYvT0Vekd0CNRC2328",
                view: 2,
                iconText: "豆包-",
            },
            {
                url: "https://ai.wolian.chat/openmao/#/?inviteCode=1721353838461456386",
                type: "icon",
                name: "AI论文助手",
                src: "https://files.codelife.cc/icons/ai.wolian.chat.png",
                backgroundColor: "#ffffff",
                id: "q4Jloyi72qJxjkr13KZO88873",
                iconText: "",
            },
            {
                url: "https://js.design/ai?source=itab&plan=ai",
                type: "icon",
                name: "即时AI",
                src: "https://files.codelife.cc/icons/js-design-ai.png",
                backgroundColor: "#FFFFFF",
                id: "WcR9ifg4F5NXJ4ZsHbZme8274",
                iconText: "",
                view: 1,
            },
            {
                url: "https://www.swdt.com/?utm_source=itab",
                type: "icon",
                name: "知犀AI",
                src: "https://files.codelife.cc/icons/zhixi.svg",
                backgroundColor: "#8d49d9",
                id: "JINCoSyY-lTPPRc3fGsXQ1325",
                view: 2,
                iconText: "知犀A",
            },
            {
                url: "https://www.whee.com/?channel=goitab",
                type: "icon",
                name: "WHEE",
                src: "https://files.codelife.cc/icons/whee.com.svg",
                backgroundColor: "#3549ff",
                id: "GQy_HPbVVW91003ykXzIr9485",
                view: 3,
            },
            {
                url: "https://yige.baidu.com",
                type: "icon",
                name: "文心一格",
                src: "https://files.codelife.cc/icons/yige.baidu.png",
                backgroundColor: "#ffffff",
                id: "NdjgJUz5ZQZ8-N5Z4CgjA2553",
            },
            {
                url: "https://www.gaoding.com/utms/ba46f32f055a48aab63ee74f15281593",
                type: "icon",
                name: "稿定AI绘画",
                src: "https://files.codelife.cc/icons/gaoding.svg",
                backgroundColor: "#2455f4",
                id: "Cz4F7JR9Xwz2FQ8lQk1MS1965",
                iconText: "稿定设",
                view: 2,
            },
            {
                url: "https://www.feishu.cn/product/minutes",
                type: "icon",
                name: "飞书妙记",
                src: "https://files.codelife.cc/icons/feishufeishu.png",
                backgroundColor: "#ffffff",
                id: "7hHtpc8iDuRbgqGwkJbSg4511",
            },
            {
                url: "https://aigc.wondershare.cn/",
                type: "icon",
                name: "万兴爱画",
                src: "https://files.codelife.cc/icons/aigc.wondershare.cn.svg",
                backgroundColor: "#12142f",
                id: "4Vt_zPl6iIMz2TgipoTYD1369",
                view: 1,
            },
            {
                url: "https://ibiling.cn/template?from=itabpaper03",
                type: "icon",
                name: "免费AI写作",
                src: "https://files.codelife.cc/icons/baipingai.png",
                backgroundColor: "#ffffff",
                id: "OvALL7ftka157nLXso0Fk9913",
                iconText: "心动A",
            },
        ],
    },
    {
        name: "摸鱼",
        icon: "entertainment",
        children: [
            {
                component: "games",
                insetType: "",
                name: "小游戏",
                type: "component",
                size: "1x1",
                id: "en78uPOC1seXTLoNHkhUi0078",
                view: 4,
            },
            {
                url: "http://jg.doghun.com/fast/index?gametypetg=tg&lg=11216785&client=4&ly=platform&pagetype=20&themeid=7",
                type: "icon",
                name: "热门游戏",
                src: "https://files.codelife.cc/icons/jd.doghun.png",
                backgroundColor: "#000000",
                id: "s3wVdL3FAVLwemTPj2vTf1056",
            },
            {
                id: "xiaohongshu-2",
                url: "https://www.xiaohongshu.com/explore?m_source=itab",
                type: "icon",
                name: "小红书",
                src: "https://files.codelife.cc/icons/xiaohongshu.svg",
                backgroundColor: "#ff2442",
            },
            {
                id: "RHza5iCO0",
                url: "https://weibo.com/",
                type: "icon",
                name: "新浪微博",
                src: "https://files.codelife.cc/icons/weibo.svg",
                backgroundColor: "#ffd850",
            },
            {
                id: "hBDW2dtTJ",
                url: "https://www.iqiyi.com/?vfm=f_432_dhm&fv=8648154ddd63e0af",
                type: "icon",
                name: "爱奇艺",
                src: "https://files.codelife.cc/icons/iqiyi.svg",
                backgroundColor: "#00cc4c",
                view: 1,
            },
            {
                url: "https://tophub.today/",
                type: "icon",
                name: "今日热榜",
                src: "https://files.codelife.cc/icons/tophubtopday.svg",
                backgroundColor: "#fff",
                id: "vzwxQmzGMJE2DJhUyPNs79983",
                view: 1,
            },
            {
                id: "vgXmpPPaJ",
                url: "http://www.youku.com",
                type: "icon",
                name: "优酷",
                src: "https://files.codelife.cc/icons/youku.svg",
                backgroundColor: "#ffffff",
                view: 1,
            },
            {
                id: "NnuH_lGqe",
                url: "http://v.qq.com/",
                type: "icon",
                name: "腾讯视频",
                src: "https://files.codelife.cc/icons/qqvideo.svg",
                backgroundColor: "#ffffff",
            },
            {
                id: "KHgOwEaEwALR14p0tVq_W",
                url: "https://www.bilibili.com/",
                type: "icon",
                name: "Bilibili",
                src: "https://files.codelife.cc/icons/bilibili2.svg",
                backgroundColor: "#fe65a6",
            },
            {
                id: "3kcHk8fDe",
                url: "https://www.zhihu.com/",
                type: "icon",
                name: "知乎",
                src: "https://files.codelife.cc/icons/zhihu.svg",
                backgroundColor: "#0c6dfe",
            },
            {
                id: "VqqNHgaf-",
                url: "https://store.steampowered.com/",
                type: "icon",
                name: "Steam",
                src: "https://files.codelife.cc/icons/steam.svg",
                backgroundColor: "#000000",
            },
            {
                id: "-Q8KQDvzf",
                url: "https://www.douyin.com/?ug_source=pc_liangxiang_01",
                type: "icon",
                name: "抖音",
                src: "https://files.codelife.cc/icons/douyin.svg",
                backgroundColor: "#1c0b1a",
                view: 2,
                iconText: "抖音",
            },
            {
                id: "2ykpQ4jnS",
                url: "https://www.yikm.net/",
                type: "icon",
                name: "小霸王",
                src: "https://files.codelife.cc/icons/www.yikm.net.svg",
                backgroundColor: "#1499b5",
            },
            {
                id: "CSGfty1NQ",
                url: "https://www.4399.com/",
                type: "icon",
                name: "4399小游戏",
                src: "https://files.codelife.cc/icons/4399.svg",
                backgroundColor: "#f19425",
            },
            {
                id: "Ar6V8x5ep",
                url: "http://www.huya.com/",
                type: "icon",
                name: "虎牙直播",
                src: "https://files.codelife.cc/icons/huya.svg",
                backgroundColor: "#fff",
            },
            {
                id: "G7LefZAPp",
                url: "https://www.douyu.com/",
                type: "icon",
                name: "斗鱼",
                src: "https://files.codelife.cc/icons/douyu.svg",
                backgroundColor: "#ff6a2d",
            },
            {
                id: "DMW71i6ra-1",
                url: "https://rebang.today/?from=itab.link",
                type: "icon",
                name: "今日热榜",
                src: "https://files.codelife.cc/icons/rebang.today.png",
                backgroundColor: "#165dff",
                view: 1,
            },
            {
                id: "E73yZrjb-",
                url: "https://fanqienovel.com/",
                type: "icon",
                name: "番茄小说网",
                src: "https://files.codelife.cc/icons/fanqienovel.svg",
                backgroundColor: "#fff",
            },
            {
                id: "P9JTzK_tG",
                url: "https://www.xiaozhongjishu.com/?from=itab",
                type: "icon",
                name: "小众技术资源库",
                src: "https://files.codelife.cc/icons/xiaozhongjishu.com.png",
                backgroundColor: "#fff",
                view: 1,
            },
            {
                id: "oTRgyT2MF",
                url: "http://www.douban.com",
                type: "icon",
                name: "豆瓣",
                src: "https://files.codelife.cc/icons/douban.svg",
                backgroundColor: "#00c117",
            },
            {
                id: "IC2ssYXhT",
                url: "http://www.smzdm.com/?from=itab.link",
                type: "icon",
                name: "什么值得买",
                src: "https://files.codelife.cc/icons/smzdm.svg",
                backgroundColor: "#ed1c24",
            },
            {
                id: "iOtWHp7dU",
                url: "https://weread.qq.com/",
                type: "icon",
                name: "微信读书",
                src: "https://files.codelife.cc/icons/weread-qq.svg",
                backgroundColor: "#fff",
            },
            {
                id: "K7ZGh5_g727uAnbrtsNMV",
                url: "https://www.ghxi.com/",
                type: "icon",
                name: "果核剥壳",
                src: "https://files.codelife.cc/icons/ghxi.svg",
                backgroundColor: "#fff",
            },
            {
                id: "kemoji",
                url: "https://tikolu.net/emojimix/",
                type: "icon",
                name: "emoji合成",
                src: "https://files.codelife.cc/icons/59f723c85138415abdea365b.png",
                backgroundColor: "#fff",
            },
            {
                url: "https://www.djcscs.com/index.php?uid=102271",
                type: "icon",
                name: "熊猫DJ音乐网",
                src: "https://files.codelife.cc/icons/djcscs.webp",
                backgroundColor: "",
                id: "0GKgvUXXztKysrGeCJZV45721",
            },
        ],
        id: "nav_WjjuUHrlw",
    },
];

export const siderIcons = [
    {
        name: "主页",
        icon: "home",
    },
    {
        name: "常用",
        icon: "xin",
    },
    {
        name: "音乐",
        icon: "music",
    },
    {
        name: "社交",
        icon: "chat",
    },
    {
        name: "办公",
        icon: "office",
    },
    {
        name: "娱乐",
        icon: "entertainment",
    },
    {
        name: "购物",
        icon: "shop",
    },
    {
        name: "应用",
        icon: "app",
    },
    {
        name: "编程",
        icon: "code",
    },
    {
        name: "学习",
        icon: "learn",
    },
    {
        name: "阅读",
        icon: "read",
    },
    {
        name: "工具",
        icon: "tool",
    },
    {
        name: "喜欢",
        icon: "zan",
    },
    {
        name: "收集",
        icon: "collect",
    },
    {
        name: "科技",
        icon: "ApiApp",
    },
    {
        name: "旅游",
        icon: "Plane",
    },
    {
        name: "天文",
        icon: "Planet",
    },
    {
        name: "综合",
        icon: "Apps",
    },
    {
        name: "绘画",
        icon: "Darw",
    },
    {
        name: "叶子",
        icon: "Leaf",
    },
    {
        name: "图片",
        icon: "Photo",
    },
    {
        name: "图片",
        icon: "Award",
    },
    {
        name: "健康",
        icon: "fitness",
    },
    {
        name: "产品",
        icon: "Producthunt",
    },
    {
        name: "产品",
        icon: "Telegram",
    },
    {
        name: "标记",
        icon: "Flag",
    },
    {
        name: "重要",
        icon: "Bookmark",
    },
    {
        name: "桶",
        icon: "Bucket",
    },
];

export const defaultTheme: ThemeStyles = {
    "--primary-color": "#1890ff",
    "--search-height": "46px",
    "--search-radius": "23px",
    "--search-bgColor": "rgba(var(--alpha-bg), 0.5)",
    "--icon-radius": "15.54962962962963px",
    "--icon-size": "60.254814814814814px",
    "--icon-gap-x": "29.155555555555555px",
    "--icon-gap-y": "29.155555555555555px",
    "--icon-max-width": "1350px",
    "--icon-opacity": "0.58",
    "--icon-name": "block",
    "--icon-nameSize": "12px",
    "--icon-nameColor": "#2ecc71",
    "--time-size": "70px",
    "--time-font": "HarmonyOS_Sans",
    "--time-color": "#fff",
    "--time-fontWeight": "400",
    "--time-month": "inline",
    "--time-week": "inline",
    "--time-lunar": "inline",
    "--time-sec": "none",
    "--sidebar-width": "50px",
    "--sidebar-opacity": "0.4",
    "--wall-mask": "0",
    "--wall-blur": "0px",
};
export const DefaultIcon = {
    iconLayout: "custom",
    iconRadius: 16,
    iconSize: 60,
    iconX: 30,
    iconY: 30,
    name: 1,
    nameColor: "#fff",
    nameSize: 12,
    opactiy: 1,
    startAnimation: false,
    unit: "px",
    width: 1350,
    xysync: true,
};
