name: deploy-mtab
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 手动构建
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git clone
      uses: actions/checkout@v4 #冲分支拉去代码
    - name: install nodejs
      uses: actions/setup-node@v4  
      with:
        node-version: "20.10.0"
    - name: install pnpm
      run: npm i -g pnpm

    - name: install
      run: pnpm install
    - name: build
      run:  pnpm build-only
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: '124.223.41.220'
        username: 'snows_l'
        password: 'Snow100107@'
        port: '22'
        source: './dist/*'
        target: '/www/wwwroot/miraitowa.snows-l.site/dist/'
        rm: true
       
    
  
       
